### ISSUE TITLE
Suggestion d’amélioration

### ISSUE THREAD

**Issue by pwepwe973** [picsou83/compta.libremen.com#12]
J'aimerais proposer une amélioration pour le logiciel. Actuellement, lors de la vérification des écritures comptables, la surbrillance disparaît dès que la souris est retirée d'une ligne. 

Je suggère une option pour que cette surbrillance reste en place même après avoir déplacé la souris, permettant ainsi de savoir à quelle ligne ont est arrivé dans les vérifications. Cette fonctionnalité faciliterait le travail en offrant une référence visuelle continue afin de s'avoir en un coup d’œil  a quelle ligne ont est arrivé

**Comment by picsou83** [comment]
Je vais voir ce que je peux faire. Vous faites référence aux écritures dans le menu "Journaux" ?

**Comment by pwepwe973** [comment]
Oui dans le journal général

**Comment by picsou83** [comment]
La possibilité de mettre en surbrillance n'importe quelle ligne sera effective dans la version 1.110.

Ajouter dans /var/www/html/Compta/javascript/entry.js : 
document.addEventListener('contextmenu', function(e) {
				e.preventDefault();

				var target = e.target;

				// Trouver le parent <li> le plus proche
				while (target.nodeName !== 'LI' && target.parentNode) {
					target = target.parentNode;
				}

				// Ajouter ou supprimer la classe 'highlight' au clic droit
				if (target.classList.contains('listitem3')) {
					target.classList.toggle('highlight');
				}
});

**Comment by pwepwe973** [comment]
merci beaucoup, je vais tester cela

**Comment by pwepwe973** [comment]
franchement merci c'est vraiment pratique l'option avec un simple clic droit et la ligne devient jaune merci ça va faciliter les vérifications tu es très efficace

mais ce qui serait bien ce serait que lorsqu'on clique sur une autre ligne, la surbrillance se déplace au nouvel endroit sélectionné plutôt que de créer une deuxième ligne et d'être obligé de recliquer sur l'autre pour l'effacer

**Comment by picsou83** [comment]
ok voici une nouvelle version (merci chatgpt) : 

```
document.addEventListener('contextmenu', function(e) {
    var target = e.target;

    // Trouver le parent <li> le plus proche
    while (target && target.nodeName !== 'LI') {
        target = target.parentNode;
    }

    // Si aucun élément <li> n'est trouvé, laisser le clic droit se comporter normalement
    if (!target) {
        return;
    }

    e.preventDefault();

    // Retirer la surbrillance de toutes les autres lignes
    var highlightedItems = document.querySelectorAll('.listitem3.highlight');
    highlightedItems.forEach(function(item) {
        item.classList.remove('highlight');
    });

    // Ajouter la surbrillance à la ligne cliquée
    if (target.classList.contains('listitem3')) {
        target.classList.add('highlight');
    }
});
```

**Comment by pwepwe973** [comment]
merci cela fonctionne très bien  merci pour ce travail rapide et efficace

**Comment by pwepwe973** [comment]
je constate un petit problème du a cette mise a jours elle empêche de pouvoir ouvrir dans un nouvelle anglet par exemple si je veut faire clic droit sur bilan et ouvrir dans un nouvelle anglet ou fenêtre ce n'est plus possible

**Comment by picsou83** [comment]
OK, nous allons alors créer une fonction et l'appeler uniquement dans le module Journaux :

Ajouter dans /var/www/html/Compta/javascript/entry.js :

```
function selectlighting() {
    document.addEventListener('contextmenu', function(e) {
         var target = e.target;

    // Trouver le parent <li> le plus proche
    while (target && target.nodeName !== 'LI') {
        target = target.parentNode;
    }

    // Si aucun élément <li> n'est trouvé, laisser le clic droit se comporter normalement
    if (!target) {
        return;
    }

    e.preventDefault();

    // Retirer la surbrillance de toutes les autres lignes
    var highlightedItems = document.querySelectorAll('.listitem3.highlight');
    highlightedItems.forEach(function(item) {
        item.classList.remove('highlight');
    });

    // Ajouter la surbrillance à la ligne cliquée
    if (target.classList.contains('listitem3')) {
        target.classList.add('highlight');
    }
    });
}
```

Et ajouter dans le fichier /var/www/html/Compta/Perl/Base/Handler/journal.pm ligne 1319 : 

`$content .= "<script>window.addEventListener('load', selectlighting);</script> ";`

J'ajouterai tout cela dans la version 1.110.

**Comment by picsou83** [comment]
Ok voici la nouvelle version pour ne l'appliquer que sur Journaux : 

```
document.addEventListener('contextmenu', function(e) {
    var target = e.target;

    // Trouver le parent <li> le plus proche avec un parent <ul> ayant la classe "wrapper1"
    while (target && (target.nodeName !== 'LI' || !target.parentNode.classList.contains('wrapper1'))) {
        target = target.parentNode;
    }

    // Si aucun élément <li> n'est trouvé ou s'il n'a pas de parent <ul> avec la classe "wrapper1", laisser le clic droit se comporter normalement
    if (!target) {
        return;
    }

    e.preventDefault();

    // Retirer la surbrillance de toutes les autres lignes
    var highlightedItems = document.querySelectorAll('.listitem3.highlight');
    highlightedItems.forEach(function(item) {
        item.classList.remove('highlight');
    });

    // Ajouter la surbrillance à la ligne cliquée
    if (target.classList.contains('listitem3')) {
        target.classList.add('highlight');
    }
});
```

**Comment by pwepwe973** [comment]
merci

je viens de lire que tu à utilisé chatgpt sur la nouvel version que tu a envoyé c'est top!!!
