### ISSUE TITLE
Bug apres avoir dupliqué une ecriture 

### ISSUE THREAD

**Issue by pwepwe973** [picsou83/compta.libremen.com#13]
Salut Picsous83

j'ai voulu dupliquer une écriture comptable et voici l’écriture en question dans  limage ci-dessous

![scrnli_12_05_2024 03-41-09](https://github.com/picsou83/compta.libremen.com/assets/37281042/ffec60bc-a0f4-4ac8-b972-3e299140d57f)

lorsque je clic sur dupliquer l’écriture apparais avec des lignes en doublon!

![scrnli_12_05_2024 03-41-55](https://github.com/picsou83/compta.libremen.com/assets/37281042/16cab76e-1d61-4a13-b961-af3dec7cfc08)

du coup j'ai supprimé les lignes en trop qui sont apparue

et lorsque je clic sur valider je reçois ce message d'erreur :

DBD::Pg::db selectall_arrayref failed: ERROR: duplicate key value violates unique constraint "tbljournal_id_line" DETAIL: Key (id_line)=(3598) already exists. CONTEXT: SQL statement "insert into tbljournal (date_ecriture, id_facture, libelle, debit, credit, lettrage, id_line, id_entry, id_paiement, numero_compte, fiscal_year, id_client, libelle_journal, pointage, id_export, documents1, documents2, recurrent) select date_ecriture, id_facture, libelle, debit, credit, lettrage, id_line, id_entry, id_paiement, numero_compte, fiscal_year, id_client, libelle_journal, pointage, id_export, documents1, documents2, recurrent from tbljournal_staging where _token_id = $1" PL/pgSQL function record_staging(text,integer) line 15 at SQL statement at /var/www/html/Compta/Perl/Base/Handler/entry.pm line 448.

je sais pas si tu connais le déclancheur de cela?

Merci d'avance

**Comment by picsou83** [comment]
Oui, c'est un problème identifié sur le module Entry, impliquant une histoire de token_id unique qui, pour le moment, se mélange les pinceaux lors de la modification ou duplication d'une entrée. Je vais déployer la mise à jour 1.10 qui corrige ce problème.

**Comment by picsou83** [comment]
La mise à jour 1.110, qui corrige ce problème, a été déployée.

**Comment by pwepwe973** [comment]
ok merci a toi je vais procéder à la mise a jour alors
