### ISSUE TITLE
bug ou mauvais paramétrage au niveau du bilan

### ISSUE THREAD

**Issue by pwepwe973** [picsou83/compta.libremen.com#14]
Bonjour picsou83,

Mon ami comptable qui vérifiait ma comptabilité pour moi m'a dit dans un premier temps que le logiciel est un petit bijou, mais il a constaté de petits problèmes à corriger et m'a aussi fait part de quelques améliorations qui pourraient être apportées, mais ça, ce sera dans un autre sujet !

Le premier problème que je vais soumettre est au niveau du bilan :

J'ai testé pour voir avec uniquement 2 écritures dans l'exercice avec un tout nouveau container vierge afin de repartir totalement de zéro pour voir d'où vient le problème !

J'ai rentré cette première écriture pour le capital social versé :

![image](https://github.com/picsou83/compta.libremen.com/assets/37281042/17ac7da9-3514-4a73-a692-acf71525e21b)

Après cette écriture, quand je vais dans le bilan, il m'affiche cela :

![image](https://github.com/picsou83/compta.libremen.com/assets/37281042/f6f6aec5-f1b9-4282-8a41-3da369d21268)

- Avance versé sur commande, c'est le montant du capital social qui s'affiche! en plus  il y a encore aucune écriture de bien ou de service d'enregistré dans le journal!

- Bénéfice de 5000€ alors que je n'ai encore rentré aucune vente ou aucune dépense et les 5000€ correspond à aucune écriture!

- Autres immobilisations incorporelles : il y a 2000€ alors que je n'ai pas d’écriture dans ces numéros de compte! ils sont vides !
- Avance et acompte reçu sur commandes en cours -1000€ qui semble correspondre aux 1000€ du capital social !

- Réserve légale correspond au même montant que le capital social ! alors que ça doit correspondre à un pourcentage!

Et lorsque je rentre une troisième écriture qui correspond à une formation faite par moi-même, 
![image](https://github.com/picsou83/compta.libremen.com/assets/37281042/0148308f-c2ba-4ee3-a0b9-d7f8bc252df3)

Les chiffres du bilan diminue de façon significative pour me donner cela :

![image](https://github.com/picsou83/compta.libremen.com/assets/37281042/35765419-6b5b-44ec-8f17-a1b509b7fcd4)
les 5000€ de bénéfice se voit diminué subitement à 12€
les 2000# autre immo incorporelles passe a 994€

Y a-t-il un paramétrage à faire ? Ou tout cela est-il un bug ?

Cordialement,  
SYLVAIN

**Comment by pwepwe973** [comment]
je sais pas si tu a vu ce topique car il y a un souci au niveau du bilan?

**Comment by picsou83** [comment]
Je n'ai pas encore regardé, mais tout est paramétrable. Les formules actuelles sont adaptées du logiciel de comptabilité Oxygène pour **un régime simplifié** .  Il est donc possible de modifier à la volée la formule des calculs si besoin et de partager des formulaires via import-export.

Pour cela, allez dans :

Bilan => Options => Liste des formulaires => Bilan

Ensuite, cliquez sur le petit stylo pour éditer une formule.

Par exemple, pour le code AA : Immobilisations incorporelles - Fonds commercial => Solde Débit-Crédit de : 206 207

Exemple de lien :
http://89.168.38.104/base/bilan?options=10&formulaire=Bilan&code=AA

Pour information, j'utilise Teledec.fr (gratuit) pour générer les liasses fiscales à partir d'une balance, et le bilan et compte de résultat correspondent au logiciel dans mon cas.

J'essaierai de regarder dans les prochains jours s'il y a un problème quelque part en testant avec les valeurs que vous m'avez données.

**Comment by pwepwe973** [comment]
ha ok merci je vais tester alors teledec.fr merci pour ta réactivité

**Comment by picsou83** [comment]
Ok, j'ai trouvé le problème : mes formules de calcul attendent des numéros de compte à 6 chiffres, et maintenant tout fonctionne mieux (456100, 101200, 101300, 512000). Je vais voir ce que je peux faire, sachant que la seule chose obligatoire est que les 3 premiers caractères doivent correspondre à des chiffres respectant les normes du plan comptable français. C'est noté également pour la note de frais.

**Comment by pwepwe973** [comment]
@picsou83  merci pour ton efficacité

**Comment by pwepwe973** [comment]
bonjour

je viens de voir la réponse OK je vais ajouter le fichier pour voir

merci encore pour cette réactivité ce logiciel a de l'avenir c'est sur a 100%

**Comment by pwepwe973** [comment]
j'ai mis le patch et les notes de frais prennent désormais en compte les chiffres après la virgule du coup le total est correcte maintenant

**Comment by belpre** [comment]
salut pcisou83, ça va?
tu a pu corriger les bug au niveau du bilan?

**Comment by picsou83** [comment]
Oui, c'est corrigé avec la version juste au-dessus, [PatchV111.22_05_2024-20h18.tar.gz](https://github.com/picsou83/compta.libremen.com/files/15408561/PatchV111.22_05_2024-20h18.tar.gz). Je suis en train de finir un module pour envoyer les documents par mails que je souhaite ajouter à la version finale 1.111, qui sera disponible via l'image Docker. En attendant, vous pouvez sans problème utiliser ce patch via une installation manuelle.

**Comment by picsou83** [comment]
La mise à jour 1.111, qui corrige le problème, a été déployée.
