### ISSUE TITLE
Erreur interne lors de la comptabilisation des notes de frais

### ISSUE THREAD

**Issue by pwepwe973** [picsou83/compta.libremen.com#15]
Bonjour,

il y a une erreur interne lorsque l'in clique sur comptabilisation des note de frais dans le module des note de frais

![image](https://github.com/picsou83/compta.libremen.com/assets/37281042/6d01ea88-532d-4718-8bad-92636328a085)

fichier log : 
20-05-2024 07:10:11 #### INFO #### superadmin: parametres.pm => Purge du fichier de log
20-05-2024 07:11:21 ##### DIE ##### SYSTEM: File '/var/www/html/Compta/base/documents//1/2023/Facture_Bouyguestelecom_20231102.pdf' does not exist at /var/www/html/Compta/Perl/Base/Site/ndf.pm line 3165.

je pense que cela arrive lorsque un des documents est introuvable 

un jolie message d'erreur disant que tel document manque,  serait le bien venu :)

cordialement SYLVAIN

**Comment by pwepwe973** [comment]
en tout cas merci encore pour ce jolie bébé Que tu nous a crée là @picsou83 une merveille

**Comment by picsou83** [comment]
Bonjour,

Effectivement, j'ai reproduit le problème. Il y a une protection pour empêcher la suppression d'un document lié à une écriture ou à une note de frais. Cependant, si le document est supprimé ou renommé directement depuis l'emplacement /var/www/html/Compta/base/documents/, alors ce joli message d'erreur apparaît. Je vais corriger cela dans la version v1.111.

**Comment by pwepwe973** [comment]
je me suis dis cela en voyant je journal!
ok top pour la future correction

**Comment by picsou83** [comment]
La mise à jour 1.111, qui corrige le problème, a été déployée.
