### ISSUE TITLE
Solde négatif alors qu'il est sensé êtres positive !?

### ISSUE THREAD

**Issue by pwepwe973** [picsou83/compta.libremen.com#16]
Salut @picsou83,

Je partage avec toi un petit détail que j'ai remarqué au niveau des soldes dans le grand livre V1.

Par exemple, dans le compte 512 Banque, comme tu peux le voir, quand tu débites le compte 512, le solde devient négatif au lieu d'être positif !

![image](https://github.com/picsou83/compta.libremen.com/assets/37281042/3045c63c-35f7-48bc-b0eb-cacdf15a97d5)

Par exemple, dans la copie identique de ma comptabilité dans mon autre logiciel de compta, le solde est positif quand je débite le compte 512.

![image](https://github.com/picsou83/compta.libremen.com/assets/37281042/70637c47-d4b3-4d87-8327-9f64b1d7d244)

en tout cas ce logiciel me donne envie d’apprendre a programmer lol
aller bonne journée ou bonne soirée à toi

**Comment by picsou83** [comment]
Bonjour,

Le Grand Livre V1 est la version originale développée par Vincent Veyron (https://compta.libremen.com/).

En comptabilité, la position débit ou crédit du compte 512000 Banque est inversée par rapport au relevé bancaire.

Le logiciel que vous utilisez présente un affichage purement bancaire avec des notions de dépôt et retrait, ce qui peut créer une confusion si vous comparez directement les soldes comptables dans un Grand Livre avec les relevés bancaires sans prendre en compte les conventions comptables.

Lorsque le compte 512000 Banque a un solde créditeur en comptabilité, cela signifie que sur le relevé bancaire, le solde est débiteur (vous êtes donc à découvert).

De la même manière, si le compte 512000 Banque est débiteur en comptabilité, le solde est créditeur sur le relevé bancaire. Dans ce cas, vous n’êtes pas à découvert (votre solde bancaire est positif).

Pour moi, le solde négatif n'est pas une erreur.

On pourrait par contre ajouter facilement un affichage purement bancaire (dépôt, retrait et solde) pour certains comptes (512 ?) en ajoutant un bouton quelque part.

**Comment by pwepwe973** [comment]
Salut @picsou83 ,
ok je pensais que c’était juste au niveau des écriture que on inversais je je pensais pas que le solde était en général affiché de façon inversé ça fais longtemps j'ai pas touché a ciel compte je me rappelle plus ça date de l’école :) ça remonte a trop longtemps 

merci pour ta reponse
