### ISSUE TITLE
TVA dans base/tva affiche pas la tva collecté

### ISSUE THREAD

**Issue by pwepwe973** [picsou83/compta.libremen.com#18]
Salut Picsou83

j'ai remarque que la tva affiche pas la tva collecté que j'ai dans la balance seule la tva déductible est affiché et pas forcement le bon montant

**La balance**
![image](https://github.com/user-attachments/assets/a179dc56-baf3-4cba-b0f2-b3159191348c)

**Menu tva**
![image](https://github.com/user-attachments/assets/6397a2d6-938d-4606-8081-1ae6f83319c4)

**menu autre periode tva** 
![image](https://github.com/user-attachments/assets/f94fc0a2-75d3-48b0-a701-fac1df5aec49)

**Comment by picsou83** [comment]
Bonjour,

Cela va être compliqué pour moi de vous aider car je n'utilise pas du tout ce module dans ma comptabilité et donc je ne l'ai jamais modifié (c'est la version initiale du code de Vincent Veyron - Août 2016 - https://compta.libremen.com/). Si vous souhaitez que je regarde le code, il faudra me guider. Indiquez-moi dans quelle case doit être affichée certaine information et quelles sont les informations qui devraient y être par rapport au numéro de compte. Je pourrais alors vérifier comment cela a été codé.

Voici un exemple de code dans le module tva.pm :

```
$sql = q {
with t1 as (
SELECT numero_compte FROM tblcompte WHERE substring(numero_compte from 1 for 5) = '44566' AND id_client = ? AND fiscal_year = ? ORDER BY numero_compte limit 1 ),
t2 as (
SELECT numero_compte FROM tblcompte WHERE substring(numero_compte from 1 for 5) = '44567' AND id_client = ? AND fiscal_year = ? ORDER BY numero_compte limit 1 ),
t3 as (
SELECT numero_compte FROM tblcompte WHERE substring(numero_compte from 1 for 5) = '44581' AND id_client = ? AND fiscal_year = ? ORDER BY numero_compte limit 1 ),
t4 as (
SELECT numero_compte FROM tblcompte WHERE substring(numero_compte from 1 for 5) = '44551' AND id_client = ? AND fiscal_year = ? ORDER BY numero_compte limit 1 ),
t5 as (
SELECT numero_compte FROM tblcompte WHERE substring(numero_compte from 1 for 5) = '44571' AND id_client = ? AND fiscal_year = ? ORDER BY numero_compte limit 1 )
SELECT t1.numero_compte as "44566", t2.numero_compte as "44567", t3.numero_compte as "44581", t4.numero_compte as "44551", t5.numero_compte as "44571" 
FROM t1, t2, t3, t4, t5
} ;
```

**Comment by pwepwe973** [comment]
je vais essayer de m'informer auprès de  mon amie comptable afin qu'il puissent m'aider a vous aider si j'arrive a l'avoir car il est pas souvent dispo

**Comment by pwepwe973** [comment]
Salut

sinon pour moi de mon cote il y a que 44571 que j'ai besoin et qui ne s'affiche dans le calcule après pour les autre je ne saurai dire si il fonctionne ou non, moi c'est juste celui là que j'ai dans mes écriture et qui ne s'affiche pas!

donc n'est pas pis en compte dans le calcule

**Comment by picsou83** [comment]
Dans quelle case le 44571 ne s'affiche pas ?

**Comment by pwepwe973** [comment]
Salut 
dans la case numéro 8 du taux normal à 20%

et normalement un calcule est censé se faire et afficher la tva net à payer après la déduction de la TVA déductible 
en fonction du trimestre choisi mais la rien est fais juste la tva déductible qui est affiché

![image](https://github.com/user-attachments/assets/793a6437-da95-4398-96aa-b43e4c7fcaa1)

**Comment by pwepwe973** [comment]
salut @picsou83 J’espère que cela va pour toi!

je ne sais pas si mon message précédent était compréhensible je m'en excuse si c'est non!

cela est juste en dirais que la page en question ne récupère pas les infos dans la base de donnée ou alors i y a un bug qui empêche l'affichage de la tva collectée

**Comment by picsou83** [comment]
Oui, j'ai fait une petite pause pendant l'été... Je vais regarder ce que je peux faire.

**Comment by picsou83** [comment]
En regardant le code, je vois que les requêtes en base de données se basent sur default_id_tva, qui est le code TVA des comptes de classe 7.

Avez-vous configuré la TVA par défaut utilisée par ces comptes dans la configuration des comptes (tout à droite 0.00) ?

![Capture d’écran_2024-09-17_16-50-53](https://github.com/user-attachments/assets/47125393-33ad-48ca-adad-6d3584799d0b)
![Capture d’écran_2024-09-17_16-50-42](https://github.com/user-attachments/assets/b74be4c0-dd60-49df-b566-e30c6dd74439)

**Comment by pwepwe973** [comment]
Salut en tout cas j’espère que tes vacance se sont bien déroulé et que la pause t'a fait un grand bien!! :)


sinon non j'ai rien paramétré de ce que tu me montre en image

pourquoi, il faut le faire ??

moi j'ai laissé les paramètre par défaut

**Comment by pwepwe973** [comment]
j'ai fait la modification c'est toujours pareil

**Comment by picsou83** [comment]
Quel mode de TVA avez-vous sélectionné dans les paramètres de la société ? 

![Capture d’écran_2024-09-17_23-52-38](https://github.com/user-attachments/assets/d843b3e2-49f9-44e3-b8f5-a76c2a0569b8)


La sélection des données se fait comme suit en fonction du mode de TVA choisi : 

`
 if ( $args->{id_tva_option} eq 'encaissements' ) {
	#on recherche les écritures antérieures à la date butoir qui sont pointées et non lettrées
	$where_clause = ' AND date_ecriture <= ? AND pointage = FALSE AND lettrage is not null ' ;

	@bind_array = ( $r->pnotes('session')->{id_client}, $args->{fin_periode} ) ;

    } else {

	#on recherche toutes les écritures dans la période recherchée
	if ( $args->{id_tva_periode} eq 'trimestrielle' ) {
	    
	    $where_clause = ' AND fiscal_year = ? AND to_char(date_ecriture, \'Q\') = to_char(?::date, \'Q\') ' ;

	} else {

	    $where_clause = ' AND fiscal_year = ? AND to_char(date_ecriture, \'MM\') = to_char(?::date, \'MM\') ' ;
	    
	} #	if ( $args->{id_tva_periode} eq 'trimestrielle' )

	 `

**Comment by pwepwe973** [comment]
je suis au régime Reel simplifier de tva donc j'ai selectionné cela dans l'application

![FireShot Capture 111 - Wiki](https://github.com/user-attachments/assets/fe4c55df-567a-48f1-885d-7fa5bedb411e)

**Comment by picsou83** [comment]
OK, voici la documentation du module TVA. Pour une TVA collectée à l'encaissement, il est nécessaire que les comptes de classe 7 soient correctement paramétrés avec le pourcentage de TVA applicable, et que les écritures sur les comptes 7 soient lettrées et non pointées.

```
Déclaration de TVA (formulaire CA3)
Le calcul de la TVA exigible est fait à partir des montants enregistrés dans les comptes de classe 7, et du pourcentage de TVA applicable pour ces comptes (voir Comptes -> Modifier la liste). Ce calcul peut être fait sur les débits ou sur les encaissements

L'option 'TVA sur encaissements' calcule la TVA collectée sur la période à partir des comptes 7 qui sont lettrés et non pointés; il faut donc dans ce cas, pour obtenir une déclaration conforme :

Après encaissement de la facture, lettrer le ou les comptes 7 servis par l'écriture de vente
Aller dans le menu 'TVA' pour obtenir le calcul la TVA due, et valider l'opération
Pointer les écritures des comptes de classe 7 précédemment lettrées, pour qu'elles n'apparaissent plus dans les déclarations suivantes
L'option 'TVA sur débits' calcule la TVA due sur l'ensemble des factures enregistrées dans la période considérée

Il est possible dans ce cas d'enregistrer des ventes de services (TVA exigible à l'encaissement), en utilisant des comptes d'attente :

Créer un ou plusieurs compte 418 'Ventes non taxables', un compte 44578 'tva collectée non exigible', et un ou plusieurs comptes 7 paramétrés à 0% de TVA et terminés par '*'
Enregistrer les ventes dans ces comptes
Lors du règlement, extourner l'écriture initiale, puis enregistrer la vente dans les comptes 411, 4457 et les comptes de classe 7 normaux à la date du règlement
Calculer la TVA due pour la période via le menu 'TVA'
Pour calculer votre formulaire CA3 (déclaration de TVA), dans le menu 'TVA', sélectionner la période à déclarer puis cliquer sur 'Valider'; le logiciel affiche alors une réplique partielle du formulaire 3310CA3 (visible sur impots.gouv.fr), avec un calcul des champs principaux à renseigner. Les périodes de déclaration correspondent à la période en cours et celles de l'année qui précède. Le formulaire de calcul de TVA ne peut pas être utilisé pour les dates antérieures de plus de 12 mois à la date du jour, mais il est possible d'enregistrer manuellement des écritures antérieures

En cliquant sur 'Valider' en bas du formulaire, les écritures à passer sont affichées dans le formulaire de saisie d'une écriture et peuvent y être modifiées si besoin
```

**Comment by pwepwe973** [comment]
Salut we j'ai remarqué le bug aussi du coup merci pour les info je vais tester et je reviendrais vers toi 

merci encore pour ton aide precieuse

**Comment by pwepwe973** [comment]
Je reviens vers toi tu a tout réglé mon problème tu avais totalement raison c’était bien cela 

j'ai lettré et ça a fonctionné merci 1000 fois picsous83

**Comment by picsou83** [comment]
La mise à jour 1.111, qui corrige le problème, a été déployée.
