### ISSUE TITLE
Le Bilan affiche uniquement les disponibilité N-1

### ISSUE THREAD

**Issue by pwepwe973** [picsou83/compta.libremen.com#19]
Salut Picsou83

j’espère que tu va bien?!
 juste pour faire une remonter d'un petit bug au niveau du bilan

Le Bilan affiche uniquement les disponibilité N-1 et non celui de n+1

![image](https://github.com/user-attachments/assets/4b900311-8744-44b6-8784-fb40c70aad71)

**Comment by picsou83** [comment]
Je ne comprends pas très bien. Dans le bilan, s'affichent les disponibilités BRUT de l'année en cours (cases AM Solde Débit-Crédit de : 511 à 519, 53 à 54), les disponibilités NET de l'année en cours (case CM, formule AM - BM), ainsi que les disponibilités NET de l'année N-1 en case DM. Je ne comprends pas ce que vous voulez dire par les disponibilités de l'année N+1 ?

**Comment by pwepwe973** [comment]
quand jetait dans l’exercice 2023 il y avait le bon solde 1245 euro et quand je passe à l'exercice 2024 malgré tout les nombreuse écriture ajoutée y compris en 512 banque il affichait toujours en disponibilité pour 2024, 1245€ dans les 3 colonne du bilant   alors que en 512 banque le solde avait bien changé

et bizarrement la losque je vois ton message j'y retourne pour voir dans les 2 exercice là cela c'est réparé 

![image](https://github.com/user-attachments/assets/3aa3f436-d6e4-4e87-9704-825e86593832)

il affiche désormais 1159€ pour 2024 alors que j'avait tout tenté redemander le docker changer de navigateur 

c'est bizarre j'ai l'impression d'avoir la poisse ou alors je suis fou
