### ISSUE TITLE
Erreurs sur importation d'écritures

### ISSUE THREAD

**Issue by domguard** [picsou83/compta.libremen.com#6]
Bonjour
Sur un import CSV, bien formaté en UTF-8 et re-controlé ensuite dans un editeur de texte brut,
je suis bloqué par une erreur indiquant : `ligne 1 => colonne 5 : Numéro de compte *** *** est invalide et ne commence pas par un chiffre`.

Or si je suis l'aide, la colonne 5 devrait être le numéro de pièce, pas le numero de compte. 
En tout cas, sur mon fichier la colonne 5 est vide : 
`Banque;11/01/2023;;512000;;REALISATION DE PRET 00004337229 ;;90.48`

Si je me hasarde à ajouter une colonne vide avant le numero de compte pour qu'il tombe bien en colonne 5, j'ai une erreur à propos de la date qui n'est pas dans le bon exercice.

Bref, on dirait qu'il y a des différences entre le format recommandé dans l'aide et ce que le module d'importation attend ?

**Comment by picsou83** [comment]
Bonjour,

En effet, je n'ai pas mis à jour la documentation concernant l'import et l'export de fichiers depuis que j'ai repris le logiciel sur compta.libremen.com.

Pour la date, il est essentiel de sélectionner le bon exercice avant de lancer l'importation des écritures pour que les dates des écritures comptables correspondent au bon exercice. Pour votre exemple, assurez-vous de sélectionner l'exercice 2023 dans le titre en haut de la page.

Voici le format attendu au minimum (les champs avec un * peuvent être vides):
# JournalLib
# EcritureNum *
# EcritureDate
# CompteNum
# CompteLib				
# id_paiement (libre) *
# PieceRef *
# EcritureLib			
# Debit	
# Credit 				
# EcritureLet *
# ecriturepointage *
# documents1 *
# documents2 *
# date_creation *
# ValidDate *	
# exercice *
# id_export * 
....  tout le reste est optionnel.

Avec votre exemple: 
Banque;;11/01/2023;512000;BANQUE;;;REALISATION DE PRET 00004337229 ;;90.48

Vous pouvez également retrouver le format attendu en allant sur Export => CSV - Fichier de toutes les écritures pour l'exercice en cours.

**Comment by domguard** [comment]
Merci pour le format, il faut aussi le code journal en premiere colonne
Mais ça bloque maintenant avec le message `Les écritures ne sont pas dans le bon exercice (champ exercice du fichier en 22/01/2024)`
Quelle que soit la date que je mette dans la colonne exercice (date en 2023 ou 2024)
j'ai bien sélectionner le bon exercice avant de procéder à l'import

par contre, est-il vraiment obligatoire de re-indiquer le libellé du compte ?(c'etait à la base un relevé de compte "amélioré" pour saisir vite le compte banque)

**Comment by picsou83** [comment]
Je viens de vérifier, il y a plusieurs problèmes bloquants dans le code pour importer correctement des données aux formats CSV depuis le module Journaux => [Importer des écritures] => Format CSV, de plus ce module attend des écritures équilibrées.

En attendant, je vous propose plutôt d'utiliser l'une de ces méthodes :

1. Journaux => [Importer des écritures] => Format fichier FEC : concerne des écritures comptables équilibrées.

2. Menu Principal => CSV/OFX/OCR : concerne l'import des relevés bancaires :
- Tous les fichiers OFX sont normalement pris en charge avec la méthode d'importation fichier/textarea.
- Les fichiers .csv de Boursorama Banque et de Paypal.
- Les fichiers .pdf du Crédit Agricole avec Méthode d'importation OCR

Pour importer des fichiers provenant d'autres banques, il me faut des exemples avant de pouvoir les ajouter.

**Comment by domguard** [comment]
Je suis aussi au C.A. (agriculteur) mais :

- le relevé en mode OCR n'est pas reconnu, 
- l'import en CSV renvoie : "Le contenu du champ de texte ne ressemble ni à une structure CSV valide avec au moins deux lignes, ni à une structure OFX valide."
- l'import OFX marche bien, mais je ne peux pas trop l'utiliser comme je passe systematiquement par des comptes fournisseurs, et que les comptes proposés en dépenses sont uniquement les comptes de 6

**Comment by picsou83** [comment]
Vu que vous utilisez des comptes fournisseurs, avez-vous bien paramétré votre type de comptabilité en Comptabilité d'engagement ?

Paramètres => Fiche sociétés => Système comptable => Comptabilité d'engagement.

Il y a + de paramètres disponibles lors de l'import, et pas seulement des comptes de dépenses.

**Comment by domguard** [comment]
Ah oui génial, j'ai effectivement acces a tous les comptes via "autres sorties"
par contre je ne peux pas valider les ecritures générées, j'ai une erreur sur l'année fiscale : je travaille sur 2023 et visiblement le module d'import veut que ce soit 2024... récupérer l'info de la session j'imagine...
