### ISSUE TITLE
Déplacement d'ecriture impossible

### ISSUE THREAD

**Issue by domguard** [picsou83/compta.libremen.com#7]
Ce n'est pas très genant quand on le sait, 
mais le menu déroulant servant à déplacer une ecriture vers un autre journal n'a pas d'effet.

**Comment by picsou83** [comment]
Je viens d'essayer et je ne vois pas de problème :

Se positionner sur une écriture.
Sélectionner un autre journal dans le menu déroulant, puis cliquer sur OK.
Enfin, valider la modification en cliquant sur le bouton "Valider".
L'écriture sera alors bien enregistrée sur un autre journal.

**Comment by domguard** [comment]
Ah ok je n'avais pas saisi la logique de l'interface, comme la page rechargeais, je pensais que le changement de journal était déjà enregistré, et je n'appuyais donc pas sur "valider". Merci !
