### ISSUE TITLE
Variations de stock

### ISSUE THREAD

**Issue by domguard** [picsou83/compta.libremen.com#8]
Dans le fichier Bilans.pm, les références au variations de stock incluent les comptes 601 et 602, et ne le devrait pas :
```perl
if	((substr( $_->{numero_compte}, 0, 3) =~ /601|602/) || (substr( $_->{numero_compte}, 0, 4) =~ /6030|6031|6032/))
``` 
ça marche mieux avec : 
```perl
if	(substr( $_->{numero_compte}, 0, 4) =~ /6030|6031|6032/)
``` 
(4 occurences)

**Comment by domguard** [comment]
Ah si, pour le 601 il peut y avoir variation de stock...je me renseigne mieux....

**Comment by picsou83** [comment]
J'ai ajouté dans la version 1.109 un module permettant de gérer les options de calcul des différents champs pour le Bilan et le compte de résultat. J'ai utilisé toutes les formules trouvées sur le logiciel de comptabilité Oxygène pour un régime simplifié. Il sera donc possible de modifier à la volée la formule des calculs si besoin et de partager des formulaires via import-export.
![Capture d’écran_2024-03-03_19-58-49](https://github.com/picsou83/compta.libremen.com/assets/34648108/486cde88-fe1e-41e0-a24d-a21aa08b2408)

**Comment by domguard** [comment]
génial !!!
je serai très interessé d'avoir vos fichiers references pour ces formules, que ce soit celui de Teledec ou d'oxygène, parceque là j'essaye d'equilibrer mon bilan , et c'est urgent ;)
merci

**Comment by domguard** [comment]
Pour le 603, c'est effectivement Solde Débit-Crédit qui marche bien
j'ai modifié le calcul, mais il fallait autoriser la mise en forme des totaux negatifs pour qu'il soit affiché

Autres petits fix dans bilan.pm =
#$actif[5] => Immobilisations corporelles amort Crédit de : 281 291 282 292 2931
## FIX ajouter le 284 (autres immos)

#$passif[7] Provisions réglementées Solde créditeur de :	131 à 138	14 Moins le solde débiteur de :	139
Le code ne fait pas ce que dit le commentaire, a savoir soustraire le 139

Ligne 3008 de bilan.pm, affichage innoportun de $passif[12] et $passif_N1[12]

**Comment by picsou83** [comment]
Pour les fichiers de référence, j'utilise à partir de la version 1.109 les formules récupérées par cette procédure : [https://aides.memsoft.fr/aide/compta904/ordinateur/Mise_en_place_de_votre_comptabilite_generale/Parametrage_commun_a_l-ensemble_des_dossiers/Parametrage_des_rubriques_Documents_de_synthese.htm](https://aides.memsoft.fr/aide/compta904/ordinateur/Mise_en_place_de_votre_comptabilite_generale/Parametrage_commun_a_l-ensemble_des_dossiers/Parametrage_des_rubriques_Documents_de_synthese.htm)

**Comment by picsou83** [comment]
Ajout dans la version 1.109 d'un module permettant de gérer les options de calcul des différents champs pour le bilan et le compte de résultat, ainsi que pour d'éventuels formulaires. Les formules actuelles sont adaptées du logiciel de comptabilité Oxygène pour un régime simplifié. Il est donc désormais possible de modifier à la volée la formule des calculs si besoin et de partager des formulaires via import-export.
